### ISSUE TITLE
Will not build on Ionic 2

### ISSUE THREAD

**Issue by jon-cole** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#206]
After the recent updates I still get a failure with Ionic 2:

`
/platforms/android/src/com/cordovaplugincamerapreview/CameraActivity.java:354: error: cannot find symbol
                width = sizes.get(sizeList.size() - 1).width();
`

Even fixing these I get 

> Supplied parameters do not match any signature of call target.

when I try to use `CameraPreview.startCamera({x: 0, y: 0, width: window.device.width, height: window.device.height, camera: "front", toBack: false, tapPhoto: true, previewDrag: false});`

**Comment by westonganger** [comment]
This is now fixed in master. There was a compile error.

**Comment by jon-cole** [comment]
Thanks for such a speedy response!

I still can't get it to build. If I use the syntax in the readme 
`CameraPreview.startCamera({x: 0, y: 0, width: window.device.width, height: window.device.height, camera: "front", toBack: false, tapPhoto: true, previewDrag: false});`
then I get 
`Supplied parameters do not match any signature of call target.`
on build.

Am I being dense? I've not used Ionic 2 or Typescript before. Any help would be greatly appreciated!

**Comment by westonganger** [comment]
Previous readme was wrong use `window.screen.width` and `window.screen.height`

**Comment by jon-cole** [comment]
Thanks. That gets rid of the complaint about window.device but I still get the "supplied parameters" error. Is it because I need different syntax for typescript?

**Comment by westonganger** [comment]
Ya this is a typescript issue. Its probably because we dont have any typings file in this repo. 

I really hate typescript, it just makes things harder but I will add a typescript definition file though I guess...

**Comment by westonganger** [comment]
I have now added the typings in typescript/CameraPreview.d.ts. Its up to you to figure out how to use those typings. Let me know if you have errors with the typings file

**Comment by jon-cole** [comment]
Thanks again for the quick response. I'm not sure this is the root of the problem. Version 0.0.8 works, it just doesn't have any of the other fixes.

I'm going to do some more digging. I think the answer might be CameraPreview.js.

**Comment by jon-cole** [comment]
This was my fault. I had a conflict with the ionic native version of this plugin I had previously tried.
