### ISSUE TITLE
 error launching in android studio

### ISSUE THREAD

**Issue by sourcer18** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#600]
I do a basic installation of the plugin and I get this error when I launch it on android, does the plugin not work? What could be happening?

![image](https://user-images.githubusercontent.com/6040292/80197732-5831fa80-861f-11ea-9b27-a87fb68357ba.png)

**Comment by westonganger** [comment]
Hmm I just merged a PR to use the new androidx package, #599. So the current code doesnt even use the code referenced here anymore. 

Please update to master and let me know if that resolves anything.

**Comment by sourcer18** [comment]
Installed from this link again "npm install cordova-plugin-camera-preview". You mean that, install it again? It still doesn't work.

**Comment by sourcer18** [comment]
i use this to install it

![image](https://user-images.githubusercontent.com/6040292/80228635-934c2200-864f-11ea-86a1-2d80879bd908.png)

**Comment by westonganger** [comment]
Use the instructions in the readme to install the latest version from master, not from npm. Its at the very top of the readme.

**Comment by sourcer18** [comment]
Yeah!!, It has worked !!

**Comment by westonganger** [comment]
Ok good. It appears I may need to release a new version of this plugin to stop this issue from continuing for others.
